#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1348528239.693845
__CHEETAH_genTimestamp__ = 'Mon Sep 24 16:10:39 2012'
__CHEETAH_src__ = 'warnings.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Dec  8 06:01:44 2011'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class warnings(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(warnings, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<div class="warning">
\t<h2>Warning!</h2>
''')
        if VFFSL(SL,"warning_links",True) != None and len(VFFSL(SL,"warning_links",True)) > 1: # generated from line 3, col 3
            write(u'''\t\t\t<ul>
''')
            for link in VFFSL(SL,"warning_links",True): # generated from line 5, col 5
                write(u'''\t\t\t\t\t<li>There is a conflict in <a href="#''')
                _v = VFFSL(SL,"link",True) # u'$link' on line 6, col 43
                if _v is not None: write(_filter(_v, rawExpr=u'$link')) # from line 6, col 43.
                write(u'''">this group</a></li>
''')
            write(u'''\t\t\t</ul>
''')
        elif VFFSL(SL,"warning_links",True) != None and len(VFFSL(SL,"warning_links",True)) == 1: # generated from line 9, col 3
            write(u'''\t\t\t<p>There is a conflict in <a href="#''')
            _v = VFFSL(SL,"warning_links",True)[0] # u'$warning_links[0]' on line 10, col 40
            if _v is not None: write(_filter(_v, rawExpr=u'$warning_links[0]')) # from line 10, col 40.
            write(u'''">this group</a></p>
''')
        elif VFFSL(SL,"warning_links",True) == None and VFFSL(SL,"warning_message",True) != None: # generated from line 11, col 3
            write(u'''\t\t\t<p>''')
            _v = VFFSL(SL,"warning_message",True) # u'$warning_message' on line 12, col 7
            if _v is not None: write(_filter(_v, rawExpr=u'$warning_message')) # from line 12, col 7.
            write(u'''</p>
''')
        write(u'''\t\t<p>Fix the problem(s) and save the item(s).</p>
</div>

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_warnings= 'respond'

## END CLASS DEFINITION

if not hasattr(warnings, '_initCheetahAttributes'):
    templateAPIClass = getattr(warnings, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(warnings)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=warnings()).run()


