#!/bin/sh

# excludes file - this contains a wildcard pattern per line of files to exclude
EXCLUDES=excludes

# the local daisylion folder
LOCALWWW=daisylion
# the local database connection info folder
LOCALDB=DB

# connection information
USERNAME=admin
SERVER=92.243.13.151

# the parent folder of the daisylion folder
SERVERWWW_PARENT=$SERVER:/srv/d_daisylion/www/
# the parent folder of the DB connection info folder
SERVERDB_PARENT=$SERVER:/srv/www/

# your SSH key
KEY=/Users/marisa/.ssh/gandi

# options
OPTS="--force --ignore-errors --delete-excluded --exclude-from=$EXCLUDES 
      --delete -a -r -v -z"

# copy the daisylion folder
rsync -e "ssh -i $KEY" $OPTS $LOCALWWW $USERNAME@$SERVERWWW_PARENT

#copy the DB folder
rsync -e "ssh -i $KEY" $OPTS $LOCALDB $USERNAME@$SERVERDB_PARENT
