#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
import daisylion.db.modules.amis.amis_export

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1348528239.15835
__CHEETAH_genTimestamp__ = 'Mon Sep 24 16:10:39 2012'
__CHEETAH_src__ = 'AmisRCTemplate31RTL.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Dec  8 06:01:44 2011'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class AmisRCTemplate31RTL(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(AmisRCTemplate31RTL, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''

// AMIS: Adaptive Multimedia Information System
// Software for playing DAISY books
// Homepage: http://amisproject.org
// 
// Copyright (c) 2008  DAISY Consortium
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// Generated by the DAISY Lion ''')
        _v = VFFSL(SL,"datetime",True) # u'$datetime' on line 24, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'$datetime')) # from line 24, col 32.
        write(u'''


''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 27, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 27, col 1.
        write(u''' "resource.h"

''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 29, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 29, col 1.
        write(u''' APSTUDIO_READONLY_SYMBOLS
/////////////////////////////////////////////////////////////////////////////
//
// Generated from the TEXTINCLUDE 2 resource.
//
''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 34, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 34, col 1.
        write(u''' "afxres.h"

/////////////////////////////////////////////////////////////////////////////
''')
        _v = VFFSL(SL,"ms_undef",True) # u'$ms_undef' on line 37, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_undef')) # from line 37, col 1.
        write(u''' APSTUDIO_READONLY_SYMBOLS

/////////////////////////////////////////////////////////////////////////////
// English (U.S.) resources

''')
        _v = VFFSL(SL,"ms_if",True) # u'$ms_if' on line 42, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_if')) # from line 42, col 1.
        write(u''' !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_ENU)
''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 43, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 43, col 1.
        write(u''' _WIN32
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
//''')
        _v = VFFSL(SL,"ms_pragma",True) # u'$ms_pragma' on line 45, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_pragma')) # from line 45, col 3.
        write(u''' code_page(1252)
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 46, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 46, col 1.
        write(u''' //_WIN32

''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 48, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 48, col 1.
        write(u''' APSTUDIO_INVOKED
/////////////////////////////////////////////////////////////////////////////
//
// TEXTINCLUDE
//

1 TEXTINCLUDE 
BEGIN
    "resource.h\\0"
END

2 TEXTINCLUDE 
BEGIN
    "''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 61, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 61, col 6.
        write(u''' ""afxres.h""\\r\\n"
    "\\0"
END

3 TEXTINCLUDE 
BEGIN
    "''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 67, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 67, col 6.
        write(u''' _AFX_NO_SPLITTER_RESOURCES\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 68, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 68, col 6.
        write(u''' _AFX_NO_OLE_RESOURCES\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 69, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 69, col 6.
        write(u''' _AFX_NO_TRACKER_RESOURCES\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 70, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 70, col 6.
        write(u''' _AFX_NO_PROPERTY_RESOURCES\\r\\n"
    "\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_if",True) # u'$ms_if' on line 72, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_if')) # from line 72, col 6.
        write(u''' !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_ENU)\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 73, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 73, col 6.
        write(u''' _WIN32\\r\\n"
    "LANGUAGE 9, 1\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_pragma",True) # u'$ms_pragma' on line 75, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_pragma')) # from line 75, col 6.
        write(u''' code_page(1252)\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 76, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 76, col 6.
        write(u''' //_WIN32\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 77, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 77, col 6.
        write(u''' ""res\\\\AmisLangpack.rc2""  // non-Microsoft Visual C++ edited resources\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 78, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 78, col 6.
        write(u''' ""afxres.rc""         // Standard components\\r\\n"
    "''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 79, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 79, col 6.
        write(u'''\\r\\n"
    "\\0"
END

''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 83, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 83, col 1.
        write(u'''    // APSTUDIO_INVOKED


/////////////////////////////////////////////////////////////////////////////
//
// DESIGNINFO
//

''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 91, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 91, col 1.
        write(u''' APSTUDIO_INVOKED
GUIDELINES DESIGNINFO 
BEGIN
    IDD_SIDEBAR, DIALOG
    BEGIN
        RIGHTMARGIN, 86
        BOTTOMMARGIN, 181
    END

    IDD_SEARCHDAISY, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 305
        TOPMARGIN, 7
        BOTTOMMARGIN, 280
    END

    IDD_GOTOPAGE, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 147
        TOPMARGIN, 7
        BOTTOMMARGIN, 66
    END

    IDD_FIND, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 185
        TOPMARGIN, 7
        BOTTOMMARGIN, 71
    END

    IDD_CDSEARCH, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 246
        TOPMARGIN, 7
        BOTTOMMARGIN, 173
    END

    IDD_ABOUTBOX, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 172
        TOPMARGIN, 7
        BOTTOMMARGIN, 115
    END

    IDD_PUBLICATIONSUMMARY, DIALOG
    BEGIN
        LEFTMARGIN, 6
        RIGHTMARGIN, 315
        TOPMARGIN, 7
        BOTTOMMARGIN, 178
    END

    IDD_OPENURL, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 258
        TOPMARGIN, 7
        BOTTOMMARGIN, 56
    END

    IDD_PREFERENCES, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 249
        TOPMARGIN, 7
        BOTTOMMARGIN, 216
    END

    IDD_TEXTSTYLE, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 165
        TOPMARGIN, 7
        BOTTOMMARGIN, 142
    END

    IDD_READING_OPTIONS, DIALOG
    BEGIN
        LEFTMARGIN, 7
        RIGHTMARGIN, 229
        TOPMARGIN, 6
        BOTTOMMARGIN, 184
    END
END
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 180, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 180, col 1.
        write(u'''    // APSTUDIO_INVOKED


/////////////////////////////////////////////////////////////////////////////
//
// Menu
//

IDR_AMISTYPE MENU 
BEGIN
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t1", False) # u'$rc.menu("t1", False)' on line 190, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t1", False)')) # from line 190, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t2") # u'$rc.menu("t2")' on line 192, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t2")')) # from line 192, col 19.
        write(u'''", \t\t\t\tID_AMIS_OPEN_FILE
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t327") # u'$rc.menu("t327")' on line 193, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t327")')) # from line 193, col 19.
        write(u'''", \t\t\tID_AMIS_OPEN_URL
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t331") # u'$rc.menu("t331")' on line 194, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t331")')) # from line 194, col 19.
        write(u'''",                      ID_AMIS_CLOSE_BOOK
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t6") # u'$rc.menu("t6")' on line 195, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t6")')) # from line 195, col 19.
        write(u'''",            ID_AMIS_LOAD_CD
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t10") # u'$rc.menu("t10")' on line 196, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t10")')) # from line 196, col 19.
        write(u'''",           ID_AMIS_SEARCH_LOCAL_DRIVES
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t13") # u'$rc.menu("t13")' on line 198, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t13")')) # from line 198, col 19.
        write(u'''",             ID_AMIS_SHOW_PREFERENCES
        MENUITEM SEPARATOR
        POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t16") # u'$rc.menu("t16")' on line 200, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t16")')) # from line 200, col 16.
        write(u'''"
        BEGIN
            MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t17") # u'$rc.menu("t17")' on line 202, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t17")')) # from line 202, col 23.
        write(u'''",                       ID_AMIS_RECENT_BOOKS_EMPTY, INACTIVE
        END
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t20") # u'$rc.menu("t20")' on line 205, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t20")')) # from line 205, col 19.
        write(u'''",               ID_AMIS_EXIT
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t26", False) # u'$rc.menu("t26", False)' on line 207, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t26", False)')) # from line 207, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t27") # u'$rc.menu("t27")' on line 209, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t27")')) # from line 209, col 19.
        write(u'''",                    ID_AMIS_TOGGLE_SIDEBAR, CHECKED
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t30") # u'$rc.menu("t30")' on line 210, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t30")')) # from line 210, col 19.
        write(u'''",       ID_AMIS_TOGGLE_VIEW
        MENUITEM SEPARATOR
        POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t334") # u'$rc.menu("t334")' on line 212, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t334")')) # from line 212, col 16.
        write(u'''"
        BEGIN
            MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t335") # u'$rc.menu("t335")' on line 214, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t335")')) # from line 214, col 23.
        write(u'''",                        ID_AMIS_NO_PAGE_STYLES, CHECKED
        END
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t38") # u'$rc.menu("t38")' on line 216, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t38")')) # from line 216, col 19.
        write(u'''",                ID_AMIS_BIGGER_FONT
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t337") # u'$rc.menu("t337")' on line 217, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t337")')) # from line 217, col 19.
        write(u'''",               ID_AMIS_SMALLER_FONT
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t340") # u'$rc.menu("t340")' on line 218, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t340")')) # from line 218, col 19.
        write(u'''",              ID_AMIS_SHOW_TEXTSTYLE
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t46", False) # u'$rc.menu("t46", False)' on line 220, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t46", False)')) # from line 220, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t47") # u'$rc.menu("t47")' on line 222, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t47")')) # from line 222, col 19.
        write(u'''",                ID_AMIS_PLAYPAUSE
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t55") # u'$rc.menu("t55")' on line 224, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t55")')) # from line 224, col 19.
        write(u'''",                ID_AMIS_ESCAPE
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t59") # u'$rc.menu("t59")' on line 226, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t59")')) # from line 226, col 19.
        write(u'''",             ID_AMIS_FASTER
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t63") # u'$rc.menu("t63")' on line 227, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t63")')) # from line 227, col 19.
        write(u'''",             ID_AMIS_SLOWER
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t67") # u'$rc.menu("t67")' on line 228, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t67")')) # from line 228, col 19.
        write(u'''",       ID_AMIS_RESET_SPEED
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t71") # u'$rc.menu("t71")' on line 230, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t71")')) # from line 230, col 19.
        write(u'''",   ID_AMIS_INCREASE_VOLUME
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t75") # u'$rc.menu("t75")' on line 231, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t75")')) # from line 231, col 19.
        write(u'''", ID_AMIS_DECREASE_VOLUME
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t81", False) # u'$rc.menu("t81", False)' on line 233, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t81", False)')) # from line 233, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t82") # u'$rc.menu("t82")' on line 235, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t82")')) # from line 235, col 19.
        write(u'''",       ID_AMIS_PREVIOUS_SECTION
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t86") # u'$rc.menu("t86")' on line 236, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t86")')) # from line 236, col 19.
        write(u'''",         ID_AMIS_NEXT_SECTION
        POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t90") # u'$rc.menu("t90")' on line 237, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t90")')) # from line 237, col 16.
        write(u'''"
        BEGIN
            MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t91") # u'$rc.menu("t91")' on line 239, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t91")')) # from line 239, col 23.
        write(u'''",                       ID_AMIS_SECTION_DEPTH_EMPTY
        END
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t94") # u'$rc.menu("t94")' on line 242, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t94")')) # from line 242, col 19.
        write(u'''",       ID_AMIS_PREVIOUS_PHRASE
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t97") # u'$rc.menu("t97")' on line 243, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t97")')) # from line 243, col 19.
        write(u'''",          ID_AMIS_NEXT_PHRASE
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t100") # u'$rc.menu("t100")' on line 245, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t100")')) # from line 245, col 19.
        write(u'''",    ID_AMIS_PREVIOUS_PAGE
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t103") # u'$rc.menu("t103")' on line 246, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t103")')) # from line 246, col 19.
        write(u'''",       ID_AMIS_NEXT_PAGE
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t106") # u'$rc.menu("t106")' on line 247, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t106")')) # from line 247, col 19.
        write(u'''",       ID_AMIS_GOTO_PAGE
        MENUITEM SEPARATOR
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t109") # u'$rc.menu("t109")' on line 249, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t109")')) # from line 249, col 19.
        write(u'''",       ID_AMIS_FIND_IN_TEXT
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t115", False) # u'$rc.menu("t115", False)' on line 251, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t115", False)')) # from line 251, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t116") # u'$rc.menu("t116")' on line 253, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t116")')) # from line 253, col 19.
        write(u'''",       ID_AMIS_ADD_BOOKMARK
        MENUITEM SEPARATOR
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t122", False) # u'$rc.menu("t122", False)' on line 256, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t122", False)')) # from line 256, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t123") # u'$rc.menu("t123")' on line 258, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t123")')) # from line 258, col 19.
        write(u'''",         ID_AMIS_SHOW_READING_OPTIONS
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t343") # u'$rc.menu("t343")' on line 259, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t343")')) # from line 259, col 19.
        write(u'''",        ID_AMIS_SHOW_PUBLICATION_SUMMARY
    END
    POPUP "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t137", False) # u'$rc.menu("t137", False)' on line 261, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t137", False)')) # from line 261, col 12.
        write(u'''"
    BEGIN
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t138") # u'$rc.menu("t138")' on line 263, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t138")')) # from line 263, col 19.
        write(u'''",              ID_AMIS_SHOW_HELP_CONTENTS
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t373") # u'$rc.menu("t373")' on line 264, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t373")')) # from line 264, col 19.
        write(u'''",         ID_AMIS_SHOW_KEYBOARD_SHORTCUTS
        MENUITEM "''')
        _v = VFN(VFFSL(SL,"rc",True),"menu",False)("t141") # u'$rc.menu("t141")' on line 265, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.menu("t141")')) # from line 265, col 19.
        write(u'''",                 ID_AMIS_ABOUT
    END
END


/////////////////////////////////////////////////////////////////////////////
//
// Dialog
//

IDD_SIDEBAR DIALOGEX 0, 0, 175, 183
STYLE DS_SETFONT | DS_FIXEDSYS | DS_CONTROL | WS_CHILD | WS_VISIBLE | WS_CLIPCHILDREN | WS_BORDER
EXSTYLE WS_EX_LAYOUTRTL\r
FONT 8, "MS Shell Dlg", 0, 0, 0x0
BEGIN
    CONTROL         "Tab1",IDC_TAB,"SysTabControl32",TCS_BOTTOM,0,163,175,18
    CONTROL         "Tree1",IDC_TREE,"SysTreeView32",TVS_HASLINES | TVS_SHOWSELALWAYS | WS_BORDER | WS_TABSTOP,0,0,175,164
    CONTROL         "List1",IDC_LIST_PAGE,"SysListView32",LVS_LIST | LVS_SINGLESEL | LVS_SHOWSELALWAYS | LVS_SHAREIMAGELISTS | LVS_ALIGNLEFT | LVS_NOCOLUMNHEADER | WS_BORDER | WS_TABSTOP,0,0,175,164
END

IDD_SEARCHDAISY DIALOGEX 0, 0, 312, 287
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t167") # u'$rc.s("t167")' on line 288, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t167")')) # from line 288, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t168") # u'$rc.s("t168")' on line 291, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t168")')) # from line 291, col 22.
        write(u'''",IDC_SEARCHINSTRUCTIONS,7,7,298,30
    EDITTEXT        IDC_SEARCHPATH,7,39,245,14,ES_AUTOHSCROLL
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t260") # u'$rc.s("t260")' on line 293, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t260")')) # from line 293, col 22.
        write(u'''",IDC_BROWSE,260,39,45,13
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t170") # u'$rc.s("t170")' on line 294, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t170")')) # from line 294, col 22.
        write(u'''",IDC_STARTSEARCH,103,63,50,15
    CTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t176") # u'$rc.s("t176")' on line 295, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t176")')) # from line 295, col 22.
        write(u'''",IDC_SEARCHING,7,92,298,13,NOT WS_VISIBLE
    LISTBOX         IDC_FILESFOUND,7,105,298,156,LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t183") # u'$rc.s("t183")' on line 297, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t183")')) # from line 297, col 22.
        write(u'''",IDC_OPENBOOK,103,266,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 298, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 298, col 22.
        write(u'''",IDCANCEL,158,266,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t173") # u'$rc.s("t173")' on line 299, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t173")')) # from line 299, col 22.
        write(u'''",IDC_STOPSEARCH,158,63,50,15
END

IDD_GOTOPAGE DIALOGEX 0, 0, 154, 73
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t231") # u'$rc.s("t231")' on line 305, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t231")')) # from line 305, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t236") # u'$rc.s("t236")' on line 308, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t236")')) # from line 308, col 22.
        write(u'''",IDC_GOTOPAGE_CAPTION,7,7,140,20
    EDITTEXT        IDC_PAGENUM,7,27,86,14,ES_AUTOHSCROLL
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 310, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 310, col 22.
        write(u'''",IDOK,23,52,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 311, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 311, col 22.
        write(u'''",IDCANCEL,82,52,50,14
END

IDD_FIND DIALOGEX 0, 0, 192, 78
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t146") # u'$rc.s("t146")' on line 317, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t146")')) # from line 317, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t147") # u'$rc.s("t147")' on line 320, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t147")')) # from line 320, col 22.
        write(u'''",IDC_FIND_DESCRIPTION,7,7,178,8
    EDITTEXT        IDC_SEARCHSTRING,7,22,178,13,ES_AUTOHSCROLL
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t152") # u'$rc.s("t152")' on line 322, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t152")')) # from line 322, col 22.
        write(u'''",IDC_FINDPREVIOUS,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,41,178,10
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 323, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 323, col 22.
        write(u'''",IDOK,42,57,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 324, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 324, col 22.
        write(u'''",IDCANCEL,99,57,50,14
END

IDD_CDSEARCH DIALOGEX 0, 0, 253, 180
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t154") # u'$rc.s("t154")' on line 330, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t154")')) # from line 330, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t155") # u'$rc.s("t155")' on line 333, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t155")')) # from line 333, col 22.
        write(u'''",IDC_MULTIVOLCD_INSTRUCTIONS,7,7,239,25
    LISTBOX         IDC_BOOKLIST,7,32,239,125,LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t157") # u'$rc.s("t157")' on line 335, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t157")')) # from line 335, col 22.
        write(u'''",IDC_OPENBOOK,73,159,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 336, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 336, col 22.
        write(u'''",IDCANCEL,130,159,50,14
END

IDD_ABOUTBOX DIALOGEX 0, 0, 179, 122
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t161") # u'$rc.s("t161")' on line 342, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t161")')) # from line 342, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    ICON            IDI_AMIS,IDC_AMISICON,11,17,21,20
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t163") # u'$rc.s("t163")' on line 346, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t163")')) # from line 346, col 22.
        write(u'''",IDC_AMISNAME,40,10,132,31,SS_NOPREFIX
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t448") # u'$rc.s("t448")' on line 347, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t448")')) # from line 347, col 22.
        write(u'''",IDC_VERSION,39,44,128,8
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t447") # u'$rc.s("t447")' on line 348, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t447")')) # from line 348, col 22.
        write(u'''",IDC_VERSIONNOTE,40,59,124,11
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t166") # u'$rc.s("t166")' on line 349, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t166")')) # from line 349, col 22.
        write(u'''",IDC_COPYRIGHT,40,75,132,16
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 350, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 350, col 22.
        write(u'''",IDOK,65,101,50,14,WS_GROUP
END

IDD_PUBLICATIONSUMMARY DIALOGEX 0, 0, 322, 186
STYLE DS_SETFONT | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t238") # u'$rc.s("t238")' on line 356, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t238")')) # from line 356, col 10.
        write(u'''"
FONT 8, "MS Sans Serif", 0, 0, 0x0
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t214") # u'$rc.s("t214")' on line 359, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t214")')) # from line 359, col 22.
        write(u'''",IDC_PUBLICATIONSUMMARYCAPTION,6,7,309,17
    CONTROL         "",IDC_SUMMARYLIST,"SysListView32",LVS_REPORT | LVS_ALIGNLEFT | LVS_NOCOLUMNHEADER | WS_BORDER | WS_TABSTOP,6,25,309,137
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 361, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 361, col 22.
        write(u'''",IDOK,137,164,50,14
END

IDD_OPENURL DIALOGEX 0, 0, 265, 63
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t368") # u'$rc.s("t368")' on line 367, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t368")')) # from line 367, col 10.
        write(u'''"
FONT 8, "MS Shell Dlg", 400, 0, 0x1
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t369") # u'$rc.s("t369")' on line 370, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t369")')) # from line 370, col 22.
        write(u'''",IDC_OPENURL_CAPTION,7,7,251,8
    EDITTEXT        IDC_URL,7,26,251,12,ES_AUTOHSCROLL
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 372, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 372, col 22.
        write(u'''",IDOK,79,42,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 373, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 373, col 22.
        write(u'''",IDCANCEL,133,42,50,14
END

IDD_PREFERENCES DIALOGEX 0, 0, 256, 223
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t218") # u'$rc.s("t218")' on line 379, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t218")')) # from line 379, col 10.
        write(u'''"
FONT 8, "MS Shell Dlg", 400, 0, 0x1
BEGIN
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t220") # u'$rc.s("t220")' on line 382, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t220")')) # from line 382, col 22.
        write(u'''",IDC_ISSELFVOICING,"Button",BS_AUTOCHECKBOX | BS_NOTIFY | WS_TABSTOP,7,7,241,10
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t221") # u'$rc.s("t221")' on line 383, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t221")')) # from line 383, col 22.
        write(u'''",IDC_SELTTSLABEL,7,22,242,8
    COMBOBOX        IDC_TTSVOICES,7,35,108,88,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t346") # u'$rc.s("t346")' on line 385, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t346")')) # from line 385, col 22.
        write(u'''",IDC_HIGHLIGHTTEXT,
                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,59,242,10
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t225") # u'$rc.s("t225")' on line 387, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t225")')) # from line 387, col 22.
        write(u'''",IDC_LOADLASTBOOK,
                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,76,242,10
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t223") # u'$rc.s("t223")' on line 389, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t223")')) # from line 389, col 22.
        write(u'''",IDC_STARTINBASICVIEW,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,94,242,10
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t347") # u'$rc.s("t347")' on line 390, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t347")')) # from line 390, col 22.
        write(u'''",IDC_PAUSEONLOSTFOCUS,
                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,112,242,10
    CONTROL         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t348") # u'$rc.s("t348")' on line 392, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t348")')) # from line 392, col 22.
        write(u'''",IDC_DISABLESCREENSAVER,
                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,130,242,10
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t349") # u'$rc.s("t349")' on line 394, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t349")')) # from line 394, col 22.
        write(u'''",IDC_CURRLANG,7,153,242,8
    COMBOBOX        IDC_INSTALLEDLANGUAGES,7,166,108,88,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    ICON            IDI_LANGICON,IDC_LANGICON,127,164,20,20
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 397, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 397, col 22.
        write(u'''",IDOK,57,202,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 398, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 398, col 22.
        write(u'''",IDCANCEL,112,202,50,14
END

IDD_TEXTSTYLE DIALOGEX 0, 0, 172, 149
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t358") # u'$rc.s("t358")' on line 404, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t358")')) # from line 404, col 10.
        write(u'''"
FONT 8, "MS Shell Dlg", 400, 0, 0x1
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t360") # u'$rc.s("t360")' on line 407, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t360")')) # from line 407, col 22.
        write(u'''",IDC_FONTLABEL,7,7,155,12
    COMBOBOX        IDC_FONT,7,20,155,63,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t362") # u'$rc.s("t362")' on line 409, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t362")')) # from line 409, col 22.
        write(u'''",IDC_HIGHLIGHTFOREGROUNDLABEL,7,45,155,11
    COMBOBOX        IDC_HIGHLIGHTFOREGROUND,7,57,155,63,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t364") # u'$rc.s("t364")' on line 411, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t364")')) # from line 411, col 22.
        write(u'''",IDC_HIGHLIGHTBACKGROUNDLABEL,7,83,156,8
    COMBOBOX        IDC_HIGHLIGHTBACKGROUND,7,98,156,52,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 413, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 413, col 22.
        write(u'''",IDOK,30,128,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 414, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 414, col 22.
        write(u'''",IDCANCEL,94,128,50,14
END

IDD_READING_OPTIONS DIALOGEX 0, 0, 236, 191
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
EXSTYLE WS_EX_LAYOUTRTL
CAPTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t187") # u'$rc.s("t187")' on line 420, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t187")')) # from line 420, col 10.
        write(u'''"
FONT 8, "MS Shell Dlg", 400, 0, 0x1
BEGIN
    LTEXT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t188") # u'$rc.s("t188")' on line 423, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t188")')) # from line 423, col 22.
        write(u'''",IDC_READING_OPTIONS_INSTRUCTIONS,7,6,222,26
    LISTBOX         IDC_OPTIONS_LIST,7,33,222,134,LBS_OWNERDRAWFIXED | LBS_HASSTRINGS | LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP
    DEFPUSHBUTTON   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t262") # u'$rc.s("t262")' on line 425, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t262")')) # from line 425, col 22.
        write(u'''",IDOK,65,170,50,14
    PUSHBUTTON      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t264") # u'$rc.s("t264")' on line 426, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t264")')) # from line 426, col 22.
        write(u'''",IDCANCEL,121,170,50,14
END


/////////////////////////////////////////////////////////////////////////////
//
// Bitmap
//

IDB_BOOKSHELFMAG        BITMAP                  "bookshelfmag.bmp"

/////////////////////////////////////////////////////////////////////////////
//
// Version
//

VS_VERSION_INFO VERSIONINFO
 FILEVERSION 3,1,0,0
 PRODUCTVERSION 3,1,0,0
 FILEFLAGSMASK 0x37L
''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 446, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 446, col 1.
        write(u''' _DEBUG
 FILEFLAGS 0x1L
''')
        _v = VFFSL(SL,"ms_else",True) # u'$ms_else' on line 448, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_else')) # from line 448, col 1.
        write(u'''
 FILEFLAGS 0x0L
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 450, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 450, col 1.
        write(u'''
 FILEOS 0x4L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "FileDescription", "AMIS (Adaptive Multimedia Information System)"
            VALUE "FileVersion", "3, 1, 0, 0"
            VALUE "InternalName", "AMIS"
            VALUE "LegalCopyright", "Copyright (C) 2008 DAISY Consortium"
            VALUE "OriginalFilename", "AMIS.exe"
            VALUE "ProductName", "AMIS (Adaptive Multimedia Information System)"
            VALUE "ProductVersion", "3, 1, 0, 0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END


/////////////////////////////////////////////////////////////////////////////
//
// Icon
//

// Icon with lowest ID value placed first to ensure application icon
// remains consistent on all systems.
IDI_AMIS                ICON                    "amis.ico"
IDI_LANGICON            ICON                    "flag.ico"

/////////////////////////////////////////////////////////////////////////////
//
// Accelerator
//

IDR_AMISTYPE ACCELERATORS 
BEGIN
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t118") # u'$rc.k("t118")' on line 492, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t118")')) # from line 492, col 5.
        write(u''',            ID_AMIS_ADD_BOOKMARK, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t118") # u'$rc.masks("t118")' on line 492, col 53
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t118")')) # from line 492, col 53.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t419") # u'$rc.k("t419")' on line 493, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t419")')) # from line 493, col 5.
        write(u''',            ID_AMIS_DECREASE_SECTION_DEPTH, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t419") # u'$rc.masks("t419")' on line 493, col 63
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t419")')) # from line 493, col 63.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t77") # u'$rc.k("t77")' on line 494, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t77")')) # from line 494, col 5.
        write(u''',        ID_AMIS_DECREASE_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t77") # u'$rc.masks("t77")' on line 494, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t77")')) # from line 494, col 51.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t407") # u'$rc.k("t407")' on line 495, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t407")')) # from line 495, col 5.
        write(u''',        ID_AMIS_DECREASE_UI_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t407") # u'$rc.masks("t407")' on line 495, col 55
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t407")')) # from line 495, col 55.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t57") # u'$rc.k("t57")' on line 496, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t57")')) # from line 496, col 5.
        write(u''',      ID_AMIS_ESCAPE,         ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t57") # u'$rc.masks("t57")' on line 496, col 48
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t57")')) # from line 496, col 48.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t22") # u'$rc.k("t22")' on line 497, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t22")')) # from line 497, col 5.
        write(u''',          ID_AMIS_EXIT,  ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t22") # u'$rc.masks("t22")' on line 497, col 43
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t22")')) # from line 497, col 43.
        write(u'''
    VK_ADD,         ID_AMIS_FASTER,         VIRTKEY, CONTROL, NOINVERT
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t61") # u'$rc.k("t61")' on line 499, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t61")')) # from line 499, col 5.
        write(u''',    ID_AMIS_FASTER,         ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t61") # u'$rc.masks("t61")' on line 499, col 46
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t61")')) # from line 499, col 46.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t111") # u'$rc.k("t111")' on line 500, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t111")')) # from line 500, col 5.
        write(u''',            ID_AMIS_FIND_IN_TEXT,   ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t111") # u'$rc.masks("t111")' on line 500, col 55
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t111")')) # from line 500, col 55.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t422") # u'$rc.k("t422")' on line 501, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t422")')) # from line 501, col 5.
        write(u''',          ID_AMIS_FIND_NEXT_IN_TEXT, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t422") # u'$rc.masks("t422")' on line 501, col 56
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t422")')) # from line 501, col 56.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t425") # u'$rc.k("t425")' on line 502, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t425")')) # from line 502, col 5.
        write(u''',          ID_AMIS_FIND_PREVIOUS_IN_TEXT, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t425") # u'$rc.masks("t425")' on line 502, col 60
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t425")')) # from line 502, col 60.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t401") # u'$rc.k("t401")' on line 503, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t401")')) # from line 503, col 5.
        write(u''',            ID_AMIS_FOCUS_ON_SIDEBAR, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t401") # u'$rc.masks("t401")' on line 503, col 57
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t401")')) # from line 503, col 57.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t404") # u'$rc.k("t404")' on line 504, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t404")')) # from line 504, col 5.
        write(u''',            ID_AMIS_FOCUS_ON_TEXT,  ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t404") # u'$rc.masks("t404")' on line 504, col 55
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t404")')) # from line 504, col 55.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t108") # u'$rc.k("t108")' on line 505, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t108")')) # from line 505, col 5.
        write(u''',            ID_AMIS_GOTO_PAGE,      ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t108") # u'$rc.masks("t108")' on line 505, col 55
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t108")')) # from line 505, col 55.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t428") # u'$rc.k("t428")' on line 506, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t428")')) # from line 506, col 5.
        write(u''',            ID_AMIS_INCREASE_SECTION_DEPTH, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t428") # u'$rc.masks("t428")' on line 506, col 63
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t428")')) # from line 506, col 63.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t73") # u'$rc.k("t73")' on line 507, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t73")')) # from line 507, col 5.
        write(u''',          ID_AMIS_INCREASE_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t73") # u'$rc.masks("t73")' on line 507, col 53
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t73")')) # from line 507, col 53.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t410") # u'$rc.k("t410")' on line 508, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t410")')) # from line 508, col 5.
        write(u''',          ID_AMIS_INCREASE_UI_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t410") # u'$rc.masks("t410")' on line 508, col 57
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t410")')) # from line 508, col 57.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t8") # u'$rc.k("t8")' on line 509, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t8")')) # from line 509, col 5.
        write(u''',            ID_AMIS_LOAD_CD,        ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t8") # u'$rc.masks("t8")' on line 509, col 53
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t8")')) # from line 509, col 53.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t105") # u'$rc.k("t105")' on line 510, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t105")')) # from line 510, col 5.
        write(u''',       ID_AMIS_NEXT_PAGE,      ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t105") # u'$rc.masks("t105")' on line 510, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t105")')) # from line 510, col 50.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t99") # u'$rc.k("t99")' on line 511, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t99")')) # from line 511, col 5.
        write(u''',       ID_AMIS_NEXT_PHRASE,    ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t99") # u'$rc.masks("t99")' on line 511, col 49
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t99")')) # from line 511, col 49.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t88") # u'$rc.k("t88")' on line 512, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t88")')) # from line 512, col 5.
        write(u''',        ID_AMIS_NEXT_SECTION,   ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t88") # u'$rc.masks("t88")' on line 512, col 50
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t88")')) # from line 512, col 50.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t4") # u'$rc.k("t4")' on line 513, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t4")')) # from line 513, col 5.
        write(u''',            ID_AMIS_OPEN_FILE,      ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t4") # u'$rc.masks("t4")' on line 513, col 53
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t4")')) # from line 513, col 53.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t329") # u'$rc.k("t329")' on line 514, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t329")')) # from line 514, col 5.
        write(u''',            ID_AMIS_OPEN_URL,       ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t329") # u'$rc.masks("t329")' on line 514, col 55
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t329")')) # from line 514, col 55.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t53") # u'$rc.k("t53")' on line 515, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t53")')) # from line 515, col 5.
        write(u''',       ID_AMIS_PLAYPAUSE,      ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t53") # u'$rc.masks("t53")' on line 515, col 49
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t53")')) # from line 515, col 49.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t102") # u'$rc.k("t102")' on line 516, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t102")')) # from line 516, col 5.
        write(u''',        ID_AMIS_PREVIOUS_PAGE,  ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t102") # u'$rc.masks("t102")' on line 516, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t102")')) # from line 516, col 51.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t96") # u'$rc.k("t96")' on line 517, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t96")')) # from line 517, col 5.
        write(u''',        ID_AMIS_PREVIOUS_PHRASE, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t96") # u'$rc.masks("t96")' on line 517, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t96")')) # from line 517, col 51.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t84") # u'$rc.k("t84")' on line 518, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t84")')) # from line 518, col 5.
        write(u''',          ID_AMIS_PREVIOUS_SECTION, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t84") # u'$rc.masks("t84")' on line 518, col 54
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t84")')) # from line 518, col 54.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t431") # u'$rc.k("t431")' on line 519, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t431")')) # from line 519, col 5.
        write(u''',            ID_AMIS_RESET_HIGHLIGHT_COLORS, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t431") # u'$rc.masks("t431")' on line 519, col 63
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t431")')) # from line 519, col 63.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t69") # u'$rc.k("t69")' on line 520, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t69")')) # from line 520, col 5.
        write(u''',            ID_AMIS_RESET_SPEED,    ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t69") # u'$rc.masks("t69")' on line 520, col 54
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t69")')) # from line 520, col 54.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t432") # u'$rc.k("t432")' on line 521, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t432")')) # from line 521, col 5.
        write(u''',          ID_AMIS_SHOW_HELP_CONTENTS, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t432") # u'$rc.masks("t432")' on line 521, col 57
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t432")')) # from line 521, col 57.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t65") # u'$rc.k("t65")' on line 522, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t65")')) # from line 522, col 5.
        write(u''',   ID_AMIS_SLOWER,         ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t65") # u'$rc.masks("t65")' on line 522, col 45
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t65")')) # from line 522, col 45.
        write(u'''
    VK_SUBTRACT,    ID_AMIS_SLOWER,         VIRTKEY, CONTROL, NOINVERT
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t433") # u'$rc.k("t433")' on line 524, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t433")')) # from line 524, col 5.
        write(u''',            ID_AMIS_TOGGLE_AUDIO_CONTENT_PLAYBACK, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t433") # u'$rc.masks("t433")' on line 524, col 70
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t433")')) # from line 524, col 70.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t398") # u'$rc.k("t398")' on line 525, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t398")')) # from line 525, col 5.
        write(u''',            ID_AMIS_TOGGLE_AUDIO_SELFVOICING_PLAYBACK, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t398") # u'$rc.masks("t398")' on line 525, col 74
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t398")')) # from line 525, col 74.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t32") # u'$rc.k("t32")' on line 526, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t32")')) # from line 526, col 5.
        write(u''',         ID_AMIS_TOGGLE_VIEW,    ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t32") # u'$rc.masks("t32")' on line 526, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t32")')) # from line 526, col 51.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t413") # u'$rc.k("t413")' on line 527, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t413")')) # from line 527, col 5.
        write(u''',        ID_AMIS_DECREASE_CONTENT_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t413") # u'$rc.masks("t413")' on line 527, col 60
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t413")')) # from line 527, col 60.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t416") # u'$rc.k("t416")' on line 528, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t416")')) # from line 528, col 5.
        write(u''',        ID_AMIS_INCREASE_CONTENT_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t416") # u'$rc.masks("t416")' on line 528, col 60
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t416")')) # from line 528, col 60.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t445") # u'$rc.k("t445")' on line 529, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t445")')) # from line 529, col 5.
        write(u''',        ID_AMIS_DECREASE_TTS_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t445") # u'$rc.masks("t445")' on line 529, col 56
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t445")')) # from line 529, col 56.
        write(u'''
    ''')
        _v = VFN(VFFSL(SL,"rc",True),"k",False)("t442") # u'$rc.k("t442")' on line 530, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.k("t442")')) # from line 530, col 5.
        write(u''',        ID_AMIS_INCREASE_TTS_VOLUME, ''')
        _v = VFN(VFFSL(SL,"rc",True),"masks",False)("t442") # u'$rc.masks("t442")' on line 530, col 56
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.masks("t442")')) # from line 530, col 56.
        write(u'''
END


/////////////////////////////////////////////////////////////////////////////
//
// String Table
//

STRINGTABLE 
BEGIN
    IDR_MAINFRAME           "AMIS"
    IDR_AMISTYPE            "\\nAMIS\\nAMIS\\nAMIS\\n"
END

STRINGTABLE 
BEGIN
    AFX_IDS_APP_TITLE       "AMIS"
    AFX_IDS_IDLEMESSAGE     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t280") # u'$rc.s("t280")' on line 548, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t280")')) # from line 548, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    ID_INDICATOR_EXT        "EXT"
    ID_INDICATOR_CAPS       "CAP"
    ID_INDICATOR_NUM        "NUM"
    ID_INDICATOR_SCRL       "SCRL"
    ID_INDICATOR_OVR        "OVR"
    ID_INDICATOR_REC        "REC"
END

STRINGTABLE 
BEGIN
    AFX_IDS_SCRESTORE       "Restore the window to normal size"
    AFX_IDS_SCTASKLIST      "Activate Task List"
    AFX_IDS_MDICHILD        "Activate this window"
END

STRINGTABLE 
BEGIN
    IDS_PROPSHT_CAPTION     "NOT USED (said Preferences)"
    IDS_META_TITLE          "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t240") # u'$rc.s("t240")' on line 571, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t240")')) # from line 571, col 30.
        write(u'''"
    IDS_META_AUTHOR         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t241") # u'$rc.s("t241")' on line 572, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t241")')) # from line 572, col 30.
        write(u'''"
    IDS_META_PUBLISHER      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t242") # u'$rc.s("t242")' on line 573, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t242")')) # from line 573, col 30.
        write(u'''"
    IDS_META_DESCRIPTION    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t243") # u'$rc.s("t243")' on line 574, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t243")')) # from line 574, col 30.
        write(u'''"
    IDS_META_NARRATOR       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t351") # u'$rc.s("t351")' on line 575, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t351")')) # from line 575, col 30.
        write(u'''"
    IDS_META_TOTAL_DURATION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t249") # u'$rc.s("t249")' on line 576, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t249")')) # from line 576, col 30.
        write(u'''"
    IDS_META_TOTAL_PAGES    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t352") # u'$rc.s("t352")' on line 577, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t352")')) # from line 577, col 30.
        write(u'''"
    IDS_META_DATE           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t353") # u'$rc.s("t353")' on line 578, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t353")')) # from line 578, col 30.
        write(u'''"
    IDS_META_FORMAT         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t354") # u'$rc.s("t354")' on line 579, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t354")')) # from line 579, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    IDS_SELFOLDER_TITLE     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t282") # u'$rc.s("t282")' on line 584, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t282")')) # from line 584, col 30.
        write(u'''"
    IDS_SELFOLDER_INSTR     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t283") # u'$rc.s("t283")' on line 585, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t283")')) # from line 585, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    IDS_FOLDERDOESNOTEXIST  "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t285") # u'$rc.s("t285")' on line 590, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t285")')) # from line 590, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    IDS_FOLDERINVALID       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t286") # u'$rc.s("t286")' on line 595, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t286")')) # from line 595, col 30.
        write(u'''"
    IDS_FOLDERCANTBECREATED "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t287") # u'$rc.s("t287")' on line 596, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t287")')) # from line 596, col 30.
        write(u'''"
    IDS_FILE_OPEN_DAISY_BOOKS "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t284") # u'$rc.s("t284")' on line 597, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t284")')) # from line 597, col 32.
        write(u'''"
    IDS_APPLY_NEXT_PAGE_STYLE "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t446") # u'$rc.s("t446")' on line 598, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t446")')) # from line 598, col 32.
        write(u'''"
END

STRINGTABLE 
BEGIN
    AFX_IDS_SCSIZE          "Change the window size"
    AFX_IDS_SCMOVE          "Change the window position"
    AFX_IDS_SCMINIMIZE      "Reduce the window to an icon"
    AFX_IDS_SCMAXIMIZE      "Enlarge the window to full size"
    AFX_IDS_SCNEXTWINDOW    "Switch to the next document window"
    AFX_IDS_SCPREVWINDOW    "Switch to the previous document window"
END

STRINGTABLE 
BEGIN
    ID_AMIS_BIGGER_FONT     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t39") # u'$rc.s("t39")' on line 613, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t39")')) # from line 613, col 30.
        write(u'''"
    ID_AMIS_SMALLER_FONT    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t338") # u'$rc.s("t338")' on line 614, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t338")')) # from line 614, col 30.
        write(u'''"
    ID_AMIS_PLAYPAUSE       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t48") # u'$rc.s("t48")' on line 615, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t48")')) # from line 615, col 30.
        write(u'''"
    ID_AMIS_ESCAPE          "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t56") # u'$rc.s("t56")' on line 616, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t56")')) # from line 616, col 30.
        write(u'''"
    ID_AMIS_FASTER          "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t60") # u'$rc.s("t60")' on line 617, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t60")')) # from line 617, col 30.
        write(u'''"
    ID_AMIS_SLOWER          "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t64") # u'$rc.s("t64")' on line 618, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t64")')) # from line 618, col 30.
        write(u'''"
    ID_AMIS_RESET_SPEED     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t68") # u'$rc.s("t68")' on line 619, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t68")')) # from line 619, col 30.
        write(u'''"
    ID_AMIS_INCREASE_VOLUME "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t72") # u'$rc.s("t72")' on line 620, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t72")')) # from line 620, col 30.
        write(u'''"
    ID_AMIS_DECREASE_VOLUME "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t76") # u'$rc.s("t76")' on line 621, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t76")')) # from line 621, col 30.
        write(u'''"
    ID_AMIS_PREVIOUS_SECTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t83") # u'$rc.s("t83")' on line 622, col 31
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t83")')) # from line 622, col 31.
        write(u'''"
    ID_AMIS_NEXT_SECTION    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t87") # u'$rc.s("t87")' on line 623, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t87")')) # from line 623, col 30.
        write(u'''"
    ID_AMIS_PREVIOUS_PHRASE "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t95") # u'$rc.s("t95")' on line 624, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t95")')) # from line 624, col 30.
        write(u'''"
    ID_AMIS_NEXT_PHRASE     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t98") # u'$rc.s("t98")' on line 625, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t98")')) # from line 625, col 30.
        write(u'''"
    ID_AMIS_PREVIOUS_PAGE   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t101") # u'$rc.s("t101")' on line 626, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t101")')) # from line 626, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    ID_AMIS_NEXT_PAGE       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t104") # u'$rc.s("t104")' on line 631, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t104")')) # from line 631, col 30.
        write(u'''"
    ID_AMIS_GOTO_PAGE       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t107") # u'$rc.s("t107")' on line 632, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t107")')) # from line 632, col 30.
        write(u'''"
    ID_AMIS_FIND_IN_TEXT    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t110") # u'$rc.s("t110")' on line 633, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t110")')) # from line 633, col 30.
        write(u'''"
    ID_AMIS_ADD_BOOKMARK    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t117") # u'$rc.s("t117")' on line 634, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t117")')) # from line 634, col 30.
        write(u'''"
    ID_AMIS_SHOW_READING_OPTIONS 
                            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t124") # u'$rc.s("t124")' on line 636, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t124")')) # from line 636, col 30.
        write(u'''"
    ID_AMIS_SHOW_PUBLICATION_SUMMARY 
                            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t344") # u'$rc.s("t344")' on line 638, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t344")')) # from line 638, col 30.
        write(u'''"
    ID_AMIS_SHOW_HELP_CONTENTS "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t139") # u'$rc.s("t139")' on line 639, col 33
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t139")')) # from line 639, col 33.
        write(u'''"
    ID_AMIS_ABOUT           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t142") # u'$rc.s("t142")' on line 640, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t142")')) # from line 640, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    ID_AMIS_OPEN_FILE       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t3") # u'$rc.s("t3")' on line 645, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t3")')) # from line 645, col 30.
        write(u'''"
    ID_AMIS_CLOSE_BOOK      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t332") # u'$rc.s("t332")' on line 646, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t332")')) # from line 646, col 30.
        write(u'''"
    ID_AMIS_LOAD_CD         "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t7") # u'$rc.s("t7")' on line 647, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t7")')) # from line 647, col 30.
        write(u'''"
    ID_AMIS_SEARCH_LOCAL_DRIVES "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t11") # u'$rc.s("t11")' on line 648, col 34
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t11")')) # from line 648, col 34.
        write(u'''"
    ID_AMIS_SHOW_PREFERENCES "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t14") # u'$rc.s("t14")' on line 649, col 31
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t14")')) # from line 649, col 31.
        write(u'''"
    ID_AMIS_EXIT            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t21") # u'$rc.s("t21")' on line 650, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t21")')) # from line 650, col 30.
        write(u'''"
    ID_AMIS_TOGGLE_SIDEBAR  "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t28") # u'$rc.s("t28")' on line 651, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t28")')) # from line 651, col 30.
        write(u'''"
    ID_AMIS_TOGGLE_VIEW     "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t31") # u'$rc.s("t31")' on line 652, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t31")')) # from line 652, col 30.
        write(u'''"
END

STRINGTABLE 
BEGIN
    IDS_META_FEATURES       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t355") # u'$rc.s("t355")' on line 657, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t355")')) # from line 657, col 30.
        write(u'''"
    IDS_META_CURRENT_PAGE   "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t356") # u'$rc.s("t356")' on line 658, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t356")')) # from line 658, col 30.
        write(u'''"
    IDS_META_CURRENT_SECTION "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t215") # u'$rc.s("t215")' on line 659, col 31
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t215")')) # from line 659, col 31.
        write(u'''"
    IDS_META_MAX_SECTION_DEPTH "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t245") # u'$rc.s("t245")' on line 660, col 33
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t245")')) # from line 660, col 33.
        write(u'''"
    IDS_META_TOC_ENTRIES    "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t244") # u'$rc.s("t244")' on line 661, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t244")')) # from line 661, col 30.
        write(u'''"
    IDS_META_SECTION_CONTENTS_LIST "''')
        _v = VFN(VFFSL(SL,"rc",True),"join_and_prefix_with_int_token",False)(("t217", "t216")) # u'$rc.join_and_prefix_with_int_token(("t217", "t216"))' on line 662, col 37
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.join_and_prefix_with_int_token(("t217", "t216"))')) # from line 662, col 37.
        write(u'''"
    IDS_META_SECTION_CONTENTS "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t390") # u'$rc.s("t390")' on line 663, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t390")')) # from line 663, col 32.
        write(u'''"
    IDS_NOT_AVAILABLE       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t288") # u'$rc.s("t288")' on line 664, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t288")')) # from line 664, col 30.
        write(u'''"
    IDS_SEARCHING           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t177") # u'$rc.s("t177")' on line 665, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t177")')) # from line 665, col 30.
        write(u'''"
    IDS_SEARCH_STOPPED      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t178") # u'$rc.s("t178")' on line 666, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t178")')) # from line 666, col 30.
        write(u'''"
    IDS_NO_FILES_FOUND      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t179") # u'$rc.s("t179")' on line 667, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t179")')) # from line 667, col 30.
        write(u'''"
    IDS_ONE_FILE_FOUND      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t180") # u'$rc.s("t180")' on line 668, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t180")')) # from line 668, col 30.
        write(u'''"
    IDS_FILES_FOUND         "''')
        _v = VFN(VFFSL(SL,"rc",True),"join_and_prefix_with_int_token",False)(("t181",)) # u'$rc.join_and_prefix_with_int_token(("t181",))' on line 669, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.join_and_prefix_with_int_token(("t181",))')) # from line 669, col 30.
        write(u'''"
    IDS_NO_BOOKS_ON_CD      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t326") # u'$rc.s("t326")' on line 670, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t326")')) # from line 670, col 30.
        write(u'''"
    IDS_PLEASE_RESTART      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t325") # u'$rc.s("t325")' on line 671, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t325")')) # from line 671, col 30.
        write(u'''"
\tIDS_BOOKMARK\t\t\t"''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t438") # u'$rc.s("t438")' on line 672, col 18
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t438")')) # from line 672, col 18.
        write(u'''"
END

STRINGTABLE 
BEGIN
    IDS_ERROR_OPENING_RELOADING 
                            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t382") # u'$rc.s("t382")' on line 678, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t382")')) # from line 678, col 30.
        write(u'''"
    IDS_ERROR_OPENING       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t314") # u'$rc.s("t314")' on line 679, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t314")')) # from line 679, col 30.
        write(u'''"
    IDS_NAVIGATION          "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t272") # u'$rc.s("t272")' on line 680, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t272")')) # from line 680, col 30.
        write(u'''"
    IDS_SECTIONS            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t273") # u'$rc.s("t273")' on line 681, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t273")')) # from line 681, col 30.
        write(u'''"
    IDS_PAGES               "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t274") # u'$rc.s("t274")' on line 682, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t274")')) # from line 682, col 30.
        write(u'''"
    IDS_FOOTNOTES           "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t275") # u'$rc.s("t275")' on line 683, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t275")')) # from line 683, col 30.
        write(u'''"
    IDS_PRODUCER_NOTES      "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t276") # u'$rc.s("t276")' on line 684, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t276")')) # from line 684, col 30.
        write(u'''"
    IDS_SIDEBARS            "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t277") # u'$rc.s("t277")' on line 685, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t277")')) # from line 685, col 30.
        write(u'''"
    IDS_GROUPED_ITEMS       "''')
        _v = VFN(VFFSL(SL,"rc",True),"s",False)("t278") # u'$rc.s("t278")' on line 686, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'$rc.s("t278")')) # from line 686, col 30.
        write(u'''"
END

''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 689, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 689, col 1.
        write(u'''    // English (U.S.) resources
/////////////////////////////////////////////////////////////////////////////



''')
        _v = VFFSL(SL,"ms_ifndef",True) # u'$ms_ifndef' on line 694, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifndef')) # from line 694, col 1.
        write(u''' APSTUDIO_INVOKED
/////////////////////////////////////////////////////////////////////////////
//
// Generated from the TEXTINCLUDE 3 resource.
//
''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 699, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 699, col 1.
        write(u''' _AFX_NO_SPLITTER_RESOURCES
''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 700, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 700, col 1.
        write(u''' _AFX_NO_OLE_RESOURCES
''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 701, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 701, col 1.
        write(u''' _AFX_NO_TRACKER_RESOURCES
''')
        _v = VFFSL(SL,"ms_define",True) # u'$ms_define' on line 702, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_define')) # from line 702, col 1.
        write(u''' _AFX_NO_PROPERTY_RESOURCES

''')
        _v = VFFSL(SL,"ms_if",True) # u'$ms_if' on line 704, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_if')) # from line 704, col 1.
        write(u''' !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_ENU)
''')
        _v = VFFSL(SL,"ms_ifdef",True) # u'$ms_ifdef' on line 705, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_ifdef')) # from line 705, col 1.
        write(u''' _WIN32
LANGUAGE 9, 1
''')
        _v = VFFSL(SL,"ms_pragma",True) # u'$ms_pragma' on line 707, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_pragma')) # from line 707, col 1.
        write(u''' code_page(1252)
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 708, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 708, col 1.
        write(u''' //_WIN32
''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 709, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 709, col 1.
        write(u''' "res\\AmisLangpack.rc2"  // non-Microsoft Visual C++ edited resources
''')
        _v = VFFSL(SL,"ms_include",True) # u'$ms_include' on line 710, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_include')) # from line 710, col 1.
        write(u''' "afxres.rc"         // Standard components
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 711, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 711, col 1.
        write(u'''

/////////////////////////////////////////////////////////////////////////////
''')
        _v = VFFSL(SL,"ms_endif",True) # u'$ms_endif' on line 714, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ms_endif')) # from line 714, col 1.
        write(u'''    // not APSTUDIO_INVOKED

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_AmisRCTemplate31RTL= 'respond'

## END CLASS DEFINITION

if not hasattr(AmisRCTemplate31RTL, '_initCheetahAttributes'):
    templateAPIClass = getattr(AmisRCTemplate31RTL, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(AmisRCTemplate31RTL)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=AmisRCTemplate31RTL()).run()


