#!/bin/bash
# start the lion web server
#!/bin/bash
# start the lion web server

if [ -z "$1" ]; then
    echo "usage: golion [local|web|combo]"
    exit
fi

# from http://forums.macosxhints.com/showthread.php?t=73839
## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
THIS_FILE_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
## OSX
  THIS_FILE_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi

THIS_DIR=$(dirname $THIS_FILE_PATH)

# generate the configuration files
python genlioncfg.py

# start locally or on the web server (or a combo of web being local and the db being on server)
if [ "$1" == "local" ]; then
    ./lionweb/start-the-lion "$THIS_DIR"/lion_local.cfg
elif [ "$1" == "web" ]; then
    nohup ./lionweb/start-the-lion "$THIS_DIR"/lion_web.cfg &
elif [ "$1" == "combo" ]; then
    ./lionweb/start-the-lion "$THIS_DIR"/lion_combo.cfg
fi

THIS_DIR=$(dirname $THIS_FILE_PATH)

# compile the template files
TEMPLATES_DIR="$THIS_DIR""/templates"
cd "$TEMPLATES_DIR"
cheetah compile *.tmpl
cd "$THIS_DIR"

echo "Starting..."
python main.py --config=$1
