#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0.1'
__CHEETAH_versionTuple__ = (2, 0, 1, 'final', 0)
__CHEETAH_genTime__ = 1211168791.9857969
__CHEETAH_genTimestamp__ = 'Mon May 19 10:46:31 2008'
__CHEETAH_src__ = 'xhtml.tmpl'
__CHEETAH_srcLastModified__ = 'Mon May 19 10:41:58 2008'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class xhtml(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        # 
        # Template variables:
        # 	title = page title
        # 	body = page body
        base_url = "http://192.168.1.146/style/"
        css = VFFSL(SL,"base_url",True) + "l10n.css"
        icon = VFFSL(SL,"base_url",True) + "lionicon.ico"
        logo = VFFSL(SL,"base_url",True) + "lion144.png"
        write('''
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">
\t<head>
    \t<title>''')
        _v = VFFSL(SL,"title",True) # '$title' on line 16, col 13
        if _v is not None: write(_filter(_v, rawExpr='$title')) # from line 16, col 13.
        write('''</title>
    \t<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    \t<link href="''')
        _v = VFFSL(SL,"css",True) # '$css' on line 18, col 18
        if _v is not None: write(_filter(_v, rawExpr='$css')) # from line 18, col 18.
        write('''" rel="stylesheet" type="text/css"/>
\t\t<link rel="icon" href="''')
        _v = VFFSL(SL,"icon",True) # '$icon' on line 19, col 26
        if _v is not None: write(_filter(_v, rawExpr='$icon')) # from line 19, col 26.
        write('''"/>
\t\t
  \t</head>
  \t<body>
\t\t<div id="header">
\t\t\t<img src="''')
        _v = VFFSL(SL,"logo",True) # '$logo' on line 24, col 14
        if _v is not None: write(_filter(_v, rawExpr='$logo')) # from line 24, col 14.
        write('''" 
\t\t\t\talt="logo for the DAISY Lion" height="91.5" width="108"/>
\t\t\t<h1>The DAISY Lion</h1>
\t\t\t<p>Web-based localization system</p>
\t\t</div>
\t\t''')
        _v = VFFSL(SL,"body",True) # '$body' on line 29, col 3
        if _v is not None: write(_filter(_v, rawExpr='$body')) # from line 29, col 3.
        write('''
\t</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_xhtml= 'respond'

## END CLASS DEFINITION

if not hasattr(xhtml, '_initCheetahAttributes'):
    templateAPIClass = getattr(xhtml, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(xhtml)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=xhtml()).run()


