#!/bin/bash
# compile the templates before using them.  delete backup files.

cd ./templates
cheetah compile *.tmpl
echo "Removing backup files"
rm -fv *.bak
cd ../
echo "Starting..."
# for the server, use this instead:
# nohup python main.py &
python main.py
