#!/bin/bash
# start the lion web server

if [ -z "$1" ]; then
    echo "usage:  [local|web|combo]"
    exit
fi

# from http://forums.macosxhints.com/showthread.php?t=73839
## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
THIS_FILE_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
## OSX
  THIS_FILE_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi

THIS_DIR=$(dirname $THIS_FILE_PATH)

# generate the configuration file for the option
python "$THIS_DIR"/../config/generate_config.py --type=$1 > "$THIS_DIR"/../config/lion.cfg

# compile the template files
TEMPLATES_DIR="$THIS_DIR"/../web/templates
echo "Compiling Cheetah templates in $TEMPLATES_DIR"
cd "$TEMPLATES_DIR"
rm -rf *.pyc
rm -rf *.py
cheetah compile *.tmpl
# restore this empty file
touch "__init__.py"
cd "$THIS_DIR"

echo "Starting..."
python ../web/main.py "$THIS_DIR"/../config/lion.cfg
